# Site settings
title: Introduction to programming for geoscientists

name2: Gerard Gorman
address2: Room 4.92, Royal School of Mines
email2: g.gorman@imperial.ac.uk
github_username2:  ggorman
twitter_username2: gerardjgorman

name1: Nicolas Barral
address1: Room 4.88, Royal School of Mines
email1: n.barral@imperial.ac.uk
github_username1:  taupalosaurus

description: > # this means to ignore newlines until "baseurl:"

  This lecture course has two objectives: learn the basic principles of
  computer programming; become proficient at Python programming as it is
  currently one of the most commonly used languages in computational science.

baseurl: http://ggorman.github.io/Introduction-to-programming-for-geoscientists
production_url : http://ggorman.github.io/Introduction-to-programming-for-geoscientist

# Build settings
markdown: kramdown
